OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "When a ANIMALS battle starts, the one\n"
	.string "at the left of the list goes out first.\p"
	.string "So, when you get more ANIMALS in your\n"
	.string "party, try switching around the order\l"
	.string "of your ANIMALS.\p"
	.string "It could give you an advantage.$"

